spring:
  datasource:
    username: sa
    url: jdbc:sqlserver://localhost;databaseName=Demo_Springboot_RestApi;integratedSecurity=false;encrypt=false;trustServerCertificate=true
    password: 12345
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
